### ISSUE TITLE
Review and Remove CameraUsage permission

### ISSUE THREAD

**Issue by artgibson** [Path-Check/gaen-mobile#66]
## Issue type

Permissions
## Version 
- Release build version: 
NA
## Affected Devices
NA

## Affected Languages

NA
## Steps to reproduce
Review - https://github.com/Path-Check/gaen-mobile/blob/develop/ios/BT/Info.plist#L45

## Expected Behavior
Remove CameraUsage permission if no longer needed.

## Current Behavior
CameraUsage is included in the permissions list

**Comment by aledustet** [comment]
Closing this since it was done here on #68
